version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d orders"]
      interval: 3s
      timeout: 3s
      retries: 10
  inventory-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d inventory"]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - inventory_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  payments-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d inventory"]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - payments_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  web:
    build: ./web
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      DJANGO_SETTINGS_MODULE: gateway.settings
      DEBUG: "1"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: "${POSTGRES_PORT}"
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
    ports:
      - "8000:8000"
    command: >
      bash -lc "python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"

  inventory:
    build: ./services/inventory
    volumes: [ "./services/inventory:/app" ]
    depends_on:
      inventory-db:
        condition: service_healthy
    ports: [ "9001:9001" ]
    command: ["uvicorn","main:app","--host","0.0.0.0","--port","9001"]
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@inventory-db:5432/inventory

  payments:
    build: ./services/payments
    volumes: [ "./services/payments:/app" ]
    depends_on:
      payments-db:
        condition: service_healthy
    ports: [ "9002:9002" ]
    command: ["uvicorn","main:app","--host","0.0.0.0","--port","9002"]
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@payments-db:5432/payments

volumes:
  db_data:
  inventory_data:
  payments_data: