version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: ./web
    depends_on: [db]
    environment:
      DJANGO_SETTINGS_MODULE: gateway.settings
      POSTGRES_DB: orders
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      DEBUG: "1"
    ports:
      - "8000:8000"
    command: >
      bash -lc "python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"

  inventory:
    build: ./services/inventory
    ports: ["9001:9001"]
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9001"]

  payments:
    build: ./services/payments
    ports: ["9002:9002"]
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9002"]

volumes:
  db_data:
