services:
  # ===== Databases =====
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_user_pass
    volumes:
      - orders_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders_user -d orders"]
      interval: 3s
      timeout: 3s
      retries: 10

  inventory-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory-pass
    volumes:
      - inventory_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory"]
      interval: 3s
      timeout: 3s
      retries: 10

  payments-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: payments-pass
    volumes:
      - payments_pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payments_user -d payments"]
      interval: 3s
      timeout: 3s
      retries: 10

  # ===== Microservicios =====
  inventory:
    build:
      context: ./services/inventory
      dockerfile: Dockerfile.prod
    env_file:
      - ./services/inventory/.env.prod
    depends_on:
      inventory-db:
        condition: service_healthy
    ports:
      - "9001:9001"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys,socket; socket.setdefaulttimeout(2); urllib.request.urlopen('http://localhost:9001/health').read(); print('OK')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s

  payments:
    build:
      context: ./services/payments
      dockerfile: Dockerfile.prod
    env_file:
      - ./services/payments/.env.prod
    depends_on:
      payments-db:
        condition: service_healthy
    ports:
      - "9002:9002"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys,socket; socket.setdefaulttimeout(2); urllib.request.urlopen('http://localhost:9002/health').read(); print('OK')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s
  # ====== Redis ======
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s

  # ===== Web (Django) =====
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    env_file:
      - ./web/.env.prod
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      inventory:
        condition: service_healthy
      payments:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys,socket; socket.setdefaulttimeout(2); urllib.request.urlopen('http://localhost:8000/health/').read(); print('OK')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s

volumes:
  orders_pg:
  inventory_pg:
  payments_pg:
